name: controller
author: vu-ase
source: github.com/VU-ASE/remote-control
version: 1.0.0
description: controller input functionality to control the rover 

commands:
  build: make build
  run: ./bin/remote-control

inputs: []

outputs:
  - decision

configuration:
  - name: controller-address
    type: string
    value: "58:10:31:A1:57:3C" 
  - name: controller-type
    type: string
    value: "ps5"
  - name: max-speed
    type: number
    value: 0.3

